# -*- encoding: utf-8 -*-

=begin
#Webhooks API

#This is the Swagger definition for the AssemblyPayment's Webhooks API

The version of the OpenAPI document: 1.0-external
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "assembly_ruby_webhooks/version"

Gem::Specification.new do |s|
  s.name        = "assembly_ruby_webhooks"
  s.version     = AssemblyRubyWebhooks::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@assemblypayments.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Webhooks API Ruby Gem"
  s.description = "This is the Swagger definition for the AssemblyPayment's Webhooks API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
