=begin
#Webhooks API

#This is the Swagger definition for the AssemblyPayment's Webhooks API

The version of the OpenAPI document: 1.0-external
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AssemblyRubyWebhooks::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @api_instance = AssemblyRubyWebhooks::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@api_instance).to be_instance_of(AssemblyRubyWebhooks::JobsApi)
    end
  end

  # unit tests for get_job
  # Show job associated to Webhook
  # Show details of a specific **Job** response using a given &#x60;:id&#x60;.
  # @param uuid ID of webhook
  # @param job_uuid ID of Job
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'get_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_jobs
  # Get jobs associated to Webhook
  # Retrieve an ordered and paginated list of the jobs garnered from a webhook using a given &#x60;:id&#x60;.
  # @param uuid ID of webhook
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of records to retrieve. Up to 200.
  # @option opts [Integer] :offset Number of records to offset. Required for pagination.
  # @option opts [String] :status Narrow down records per status
  # @return [Jobs]
  describe 'get_jobs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
