=begin
#Webhooks API

#This is the Swagger definition for the AssemblyPayment's Webhooks API

The version of the OpenAPI document: 1.0-external
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AssemblyRubyWebhooks::StatusApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @api_instance = AssemblyRubyWebhooks::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@api_instance).to be_instance_of(AssemblyRubyWebhooks::StatusApi)
    end
  end

  # unit tests for get_status
  # Check health of server
  # returns healthy if server is running fine
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
