=begin
#Webhooks API

#This is the Swagger definition for the AssemblyPayment's Webhooks API

The version of the OpenAPI document: 1.0-external
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AssemblyRubyWebhooks::WebhookSecretKeyParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AssemblyRubyWebhooks::WebhookSecretKeyParams do
  let(:instance) { AssemblyRubyWebhooks::WebhookSecretKeyParams.new }

  describe 'test an instance of WebhookSecretKeyParams' do
    it 'should create an instance of WebhookSecretKeyParams' do
      expect(instance).to be_instance_of(AssemblyRubyWebhooks::WebhookSecretKeyParams)
    end
  end
  describe 'test attribute "secret_key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
